# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/recources/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 90, 271, 71))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.urlLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.urlLabel.setFont(font)
        self.urlLabel.setObjectName("urlLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.urlLabel)
        self.urlLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.urlLineEdit.setObjectName("urlLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.urlLineEdit)
        self.soundlevelLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.soundlevelLabel.setFont(font)
        self.soundlevelLabel.setObjectName("soundlevelLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.soundlevelLabel)
        self.soundlevelSpinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.soundlevelSpinBox.setObjectName("soundlevelSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.soundlevelSpinBox)
        self.parseButton = QtWidgets.QPushButton(self.centralwidget)
        self.parseButton.setEnabled(True)
        self.parseButton.setGeometry(QtCore.QRect(20, 380, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.parseButton.setFont(font)
        self.parseButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.parseButton.setObjectName("parseButton")
        self.outputBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.outputBrowser.setGeometry(QtCore.QRect(330, 20, 431, 501))
        self.outputBrowser.setObjectName("outputBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "网易云歌曲解析"))
        self.urlLabel.setText(_translate("MainWindow", "输入歌曲 url："))
        self.soundlevelLabel.setText(_translate("MainWindow", "输入音质编码："))
        self.parseButton.setText(_translate("MainWindow", "解析!"))
import img_rc
